### ISSUE TITLE
MathJax Does Client Side Rendering

### ISSUE THREAD

**Issue by paulcavallaro** [pkhuong/pkhuong.github.io#1]
Hey, I noticed that MathJax does client-side rendering that is actually deeply slow, and non-conformant with proper web development standards such as React and Server Side Rendering.

I am providing no reproducible test case, no alternative, and of course no help in changing any of this. 

Your blog also uses one space after periods instead of two which is also wrong.

Thank you for fixing this in the next 24 hours.

**Comment by pkhuong** [comment]
I've actually been looking into pre-rendering all the math stuff, but it seems a bit fragile and annoying to deploy. Maybe once I have the blog generation workflow in a container.

I also recommend viewing the blog with a proportional font enabled.
